/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import BLL.CourseInstructorBLL;
import DTO.CourseInstructorDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QuanLyPhanCongGUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyPhanCongGUI
     */
    CourseInstructorBLL s = new CourseInstructorBLL();
    DefaultTableModel model;
    public QuanLyPhanCongGUI() throws SQLException {
        initComponents();
        listCI();
        loadTenGiangVienCBB();
        loadTenKhoaHocCBB();
        cbbMaGiangVien.setSelectedIndex(-1);
        cbbMaKhoaHoc.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMaGiangVien = new javax.swing.JTextField();
        txtMaKhoaHoc = new javax.swing.JTextField();
        cbb_TimKiem = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTenGiangVien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTenKhoaHoc = new javax.swing.JTextField();
        cbbMaGiangVien = new javax.swing.JComboBox<>();
        cbbMaKhoaHoc = new javax.swing.JComboBox<>();

        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyTyped(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã giảng viên", "Tên giảng viên", "Mã khóa học", "Tên khóa học"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã giảng viên");

        jLabel3.setText("Mã khóa học");

        txtMaGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGiangVienActionPerformed(evt);
            }
        });

        cbb_TimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên giảng viên", "Tên khóa học", "Mã giảng viên", "Mã khóa học" }));

        jLabel5.setText("Tìm kiếm");

        jLabel4.setText("Tên giảng viên");

        txtTenGiangVien.setEnabled(false);

        jLabel6.setText("Tên khóa học");

        txtTenKhoaHoc.setEnabled(false);
        txtTenKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKhoaHocActionPerformed(evt);
            }
        });

        cbbMaGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaGiangVienActionPerformed(evt);
            }
        });

        cbbMaKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbMaKhoaHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 555, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(txtTenGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(58, 58, 58)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cbbMaGiangVien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtMaGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGap(74, 74, 74)
                                            .addComponent(jLabel4))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTenKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(33, 33, 33))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMaKhoaHoc, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(23, 23, 23))
                                            .addComponent(cbbMaKhoaHoc, javax.swing.GroupLayout.Alignment.TRAILING, 0, 103, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cbb_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbb_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMaGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbbMaGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbMaKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTenGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTenKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(241, 241, 241))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGiangVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGiangVienActionPerformed

    private void txtTenKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKhoaHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKhoaHocActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        try {
            // TODO add your handling code here:
            CourseInstructorDTO ci = new CourseInstructorDTO(Integer.parseInt(txtMaKhoaHoc.getText()),Integer.parseInt(txtMaGiangVien.getText()), "", "");
            boolean isExist = s.isExistRecord(ci);
            if(isExist)
                JOptionPane.showMessageDialog(btnThem, "Giảng viên đã được phân công khóa này rồi, vui lòng chọn khóa khác");
            else{
                listCI();
                JOptionPane.showMessageDialog(btnThem, "Phân công thành công");
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void txtTimKiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyTyped
        // TODO add your handling code here:
            String value = cbb_TimKiem.getSelectedItem().toString();
            switch(value){
                case "Mã giảng viên":
                    char c = evt.getKeyChar();
                    if(!Character.isDigit(c))
                        evt.consume();
                    break;
                case "Mã khóa học":
                    char d = evt.getKeyChar();
                    if(!Character.isDigit(d))
                        evt.consume();
                    break;
            }

    }//GEN-LAST:event_txtTimKiemKeyTyped

    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTimKiemKeyPressed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        try {
            // TODO add your handling code here:
            String value = cbb_TimKiem.getSelectedItem().toString();
            switch(value){
                case "Tên giảng viên":
                    if(txtTimKiem.getText().isEmpty())
                        listCI();
                    else
                        findNameInstructor(txtTimKiem.getText());
                    break;
                case "Mã giảng viên":
                    if(txtTimKiem.getText().isEmpty())
                        listCI();
                    else
                        findIdInstructor(txtTimKiem.getText());
                    break;
                case "Tên khóa học":
                    if(txtTimKiem.getText().isEmpty())
                        listCI();
                    else
                        findNameCourse(txtTimKiem.getText());
                    break;
                case "Mã khóa học":
                    if(txtTimKiem.getText().isEmpty())
                        listCI();
                    else
                        findIdCourse(txtTimKiem.getText());
                    
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        model = (DefaultTableModel) jTable1.getModel();
        int i = jTable1.getSelectedRow();
        if(i>=0){
            txtMaGiangVien.setText(model.getValueAt(i, 1).toString());
            txtTenGiangVien.setText(model.getValueAt(i, 2).toString());
            txtMaKhoaHoc.setText(model.getValueAt(i, 3).toString());
            txtTenKhoaHoc.setText(model.getValueAt(i, 4).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(jTable1.getSelectionModel().isSelectionEmpty() == true)
            JOptionPane.showMessageDialog(btnThem, "Vui lòng chọn khóa học để xóa");
        else{
            try {
            // TODO add your handling code here:
                CourseInstructorDTO ci = new CourseInstructorDTO(Integer.parseInt(txtMaKhoaHoc.getText()), Integer.parseInt(txtMaGiangVien.getText()),txtMaKhoaHoc.getText(), txtMaGiangVien.getText());
                s.deleteCourseInstructor(ci);
                listCI();
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void cbbMaGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaGiangVienActionPerformed
        // TODO add your handling code here:
        if(cbbMaGiangVien.getSelectedIndex()==-1){
            
        }
        else
        {
            try {
                int result = s.getIdInstructorFromFullname(cbbMaGiangVien.getSelectedItem().toString());
                txtMaGiangVien.setText(Integer.toString(result));
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbbMaGiangVienActionPerformed

    private void cbbMaKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbMaKhoaHocActionPerformed
        // TODO add your handling code here:
        if(cbbMaKhoaHoc.getSelectedIndex()==-1){
            
        }
        else
        {
            try {
                int result = s.getIdCourserFromTitle(cbbMaKhoaHoc.getSelectedItem().toString());
                txtMaKhoaHoc.setText(Integer.toString(result));
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbbMaKhoaHocActionPerformed

    private void loadTenGiangVienCBB() throws SQLException{
        cbbMaGiangVien.setModel(new DefaultComboBoxModel<String>((String[]) s.readNameCourseInstructor().toArray(new String[0])));
    }
    
    private void loadTenKhoaHocCBB() throws SQLException{
        cbbMaKhoaHoc.setModel(new DefaultComboBoxModel<String>((String[]) s.readTitleCourseInstructor().toArray(new String[0])));
    }
    private DefaultTableModel convertCI(ArrayList list){
        String[] columnNames = {"TT","CourseID","Title","PersonID","FullName"};
        Object[][] data = new Object[list.size()][5];
        for(int i=0;i<list.size();i++){
            CourseInstructorDTO s = (CourseInstructorDTO) list.get(i);
            data[i][0]=i+1;
            data[i][1]=s.getCourseID();
            data[i][2]=s.getTitle();
            data[i][3]=s.getPersonID();
            data[i][4]=s.getFullName();
        }
        DefaultTableModel model = new DefaultTableModel(data,columnNames);
        return model;
    }

    private void findNameInstructor(String name) throws SQLException{
        CourseInstructorDTO ci = new CourseInstructorDTO(0,0,"",name);
        ArrayList list = s.findCourseInstructor(ci);
        DefaultTableModel model = convertCI(list);
        jTable1.setModel(model);
    }
    
    private void findNameCourse(String name) throws SQLException{
        CourseInstructorDTO ci = new CourseInstructorDTO(0,0,name,"");
        ArrayList list = s.findCourseInstructor(ci);
        DefaultTableModel model = convertCI(list);
        jTable1.setModel(model);
    }
    
    private void findIdInstructor(String name) throws SQLException{
        CourseInstructorDTO ci = new CourseInstructorDTO(0,Integer.parseInt(name),"","");
        ArrayList list = s.findCourseInstructor(ci);
        DefaultTableModel model = convertCI(list);
        jTable1.setModel(model);
    }
    
    private void findIdCourse(String name) throws SQLException{
        CourseInstructorDTO ci = new CourseInstructorDTO(Integer.parseInt(name),0,"","");
        ArrayList list = s.findCourseInstructor(ci);
        DefaultTableModel model = convertCI(list);
        jTable1.setModel(model);
    }
    
    private void listCI() throws SQLException{
        ArrayList list = s.readCourseInstructor();
        DefaultTableModel model = convertCI(list);
        jTable1.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbbMaGiangVien;
    private javax.swing.JComboBox<String> cbbMaKhoaHoc;
    private javax.swing.JComboBox<String> cbb_TimKiem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtMaGiangVien;
    private javax.swing.JTextField txtMaKhoaHoc;
    private javax.swing.JTextField txtTenGiangVien;
    private javax.swing.JTextField txtTenKhoaHoc;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
