/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import BLL.CourseBLL;
import java.awt.Dimension;
import BLL.CourseInstructorBLL;
import DTO.CourseInstructorDTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class QuanLyPhanCongGUI extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyPhanCongGUI
     */
    CourseInstructorBLL s = new CourseInstructorBLL();
    CourseBLL sBll = new CourseBLL();
    DefaultTableModel model;
    public QuanLyPhanCongGUI() throws SQLException {
        initComponents();
        listCI();
        loadTenGiangVienCBB();
        loadTenKhoaHocCBB();
        cbbTenGiangVien.setSelectedIndex(-1);
        cbbTenKhoaHoc.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDialog_OnSiteCourse = new javax.swing.JDialog();
        dgoc_txt_IDCourse = new javax.swing.JLabel();
        dgoc_txt_courseName = new javax.swing.JLabel();
        dgoc_txt_credits = new javax.swing.JLabel();
        dgoc_txt_idDepartment = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dialog_id = new javax.swing.JLabel();
        dialog_name = new javax.swing.JLabel();
        dialog_credit = new javax.swing.JLabel();
        dialog_idDepart = new javax.swing.JLabel();
        dialog_location = new javax.swing.JLabel();
        dialog_days = new javax.swing.JLabel();
        dialog_time = new javax.swing.JLabel();
        jDialog_OnlineCourse = new javax.swing.JDialog();
        dgosc_txt_IDCourse = new javax.swing.JLabel();
        dgosc_txt_courseName = new javax.swing.JLabel();
        dgosc_txt_credits = new javax.swing.JLabel();
        dgosc_txt_idDepartment = new javax.swing.JLabel();
        dgosc_txt_Location = new javax.swing.JLabel();
        dialog_OnlineId = new javax.swing.JLabel();
        dialog_onlineName = new javax.swing.JLabel();
        dialog_onlineCredit = new javax.swing.JLabel();
        dialog_onlineDep = new javax.swing.JLabel();
        dialog_onlineUrl = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        cbb_TimKiem = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        panelRadius1 = new Custom.PanelRadius();
        panelRadius3 = new Custom.PanelRadius();
        jLabel19 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbbTenGiangVien = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtMaGiangVien = new javax.swing.JTextField();
        txtMaKhoaHoc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbbTenKhoaHoc = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnThem = new Custom.ButtonRadius();
        btnSua = new Custom.ButtonRadius();
        btnXoa = new Custom.ButtonRadius();

        JDialog_OnSiteCourse.setBackground(new java.awt.Color(255, 255, 255));
        JDialog_OnSiteCourse.setSize(new Dimension(407,253));

        dgoc_txt_IDCourse.setText("ID Course:");

        dgoc_txt_courseName.setText("Name Course:");

        dgoc_txt_credits.setText("Creadits:");

        dgoc_txt_idDepartment.setText("ID Department:");

        jLabel1.setText("Location:");

        jLabel7.setText("Days");

        jLabel8.setText("Time: ");

        dialog_id.setText("id");

        dialog_name.setText("name");

        dialog_credit.setText("credits");

        dialog_idDepart.setText("idDepart");

        dialog_location.setText("location");

        dialog_days.setText("day");

        dialog_time.setText("time");

        javax.swing.GroupLayout JDialog_OnSiteCourseLayout = new javax.swing.GroupLayout(JDialog_OnSiteCourse.getContentPane());
        JDialog_OnSiteCourse.getContentPane().setLayout(JDialog_OnSiteCourseLayout);
        JDialog_OnSiteCourseLayout.setHorizontalGroup(
            JDialog_OnSiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_OnSiteCourseLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(JDialog_OnSiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dgoc_txt_courseName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dgoc_txt_credits, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dgoc_txt_idDepartment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                    .addComponent(dgoc_txt_IDCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(JDialog_OnSiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dialog_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dialog_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dialog_credit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dialog_idDepart, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(dialog_location, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dialog_days, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dialog_time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        JDialog_OnSiteCourseLayout.setVerticalGroup(
            JDialog_OnSiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JDialog_OnSiteCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JDialog_OnSiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dgoc_txt_IDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_id))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JDialog_OnSiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dgoc_txt_courseName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JDialog_OnSiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dgoc_txt_credits, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_credit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JDialog_OnSiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dgoc_txt_idDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_idDepart))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JDialog_OnSiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_location))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JDialog_OnSiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_days))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JDialog_OnSiteCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_time))
                .addContainerGap())
        );

        jDialog_OnlineCourse.setBackground(new java.awt.Color(255, 255, 255));
        jDialog_OnlineCourse.setSize(new Dimension(407,340));

        dgosc_txt_IDCourse.setText("ID Course:");

        dgosc_txt_courseName.setText("Name Course:");

        dgosc_txt_credits.setText("Credits:");

        dgosc_txt_idDepartment.setText("ID Department:");

        dgosc_txt_Location.setText("URL: ");

        dialog_OnlineId.setText("onlineId");

        dialog_onlineName.setText("onlineName");

        dialog_onlineCredit.setText("onlineCredit");

        dialog_onlineDep.setText("onlineIdDep");

        dialog_onlineUrl.setText("onlineUrl");

        javax.swing.GroupLayout jDialog_OnlineCourseLayout = new javax.swing.GroupLayout(jDialog_OnlineCourse.getContentPane());
        jDialog_OnlineCourse.getContentPane().setLayout(jDialog_OnlineCourseLayout);
        jDialog_OnlineCourseLayout.setHorizontalGroup(
            jDialog_OnlineCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_OnlineCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog_OnlineCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(dgosc_txt_idDepartment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                    .addComponent(dgosc_txt_credits, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dgosc_txt_courseName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dgosc_txt_IDCourse, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dgosc_txt_Location, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jDialog_OnlineCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dialog_onlineName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dialog_OnlineId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dialog_onlineCredit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dialog_onlineDep, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(dialog_onlineUrl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(172, Short.MAX_VALUE))
        );
        jDialog_OnlineCourseLayout.setVerticalGroup(
            jDialog_OnlineCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog_OnlineCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog_OnlineCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dgosc_txt_IDCourse, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_OnlineId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_OnlineCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dgosc_txt_courseName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_onlineName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_OnlineCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dgosc_txt_credits, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_onlineCredit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_OnlineCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dgosc_txt_idDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_onlineDep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog_OnlineCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dgosc_txt_Location, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dialog_onlineUrl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(222, 229, 238));

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyTyped(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã giảng viên", "Tên giảng viên", "Mã khóa học", "Tên khóa học"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tableMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
        }

        cbb_TimKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tên giảng viên", "Tên khóa học", "Mã giảng viên", "Mã khóa học" }));

        jLabel5.setText("Lọc theo:");

        panelRadius1.setBackground(new java.awt.Color(255, 255, 255));
        panelRadius1.setRoundBottomLeft(30);
        panelRadius1.setRoundBottomRight(30);
        panelRadius1.setRoundTopLeft(30);
        panelRadius1.setRoundTopRight(30);

        panelRadius3.setBackground(new java.awt.Color(63, 86, 185));
        panelRadius3.setRoundTopLeft(30);
        panelRadius3.setRoundTopRight(30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Information");

        javax.swing.GroupLayout panelRadius3Layout = new javax.swing.GroupLayout(panelRadius3);
        panelRadius3.setLayout(panelRadius3Layout);
        panelRadius3Layout.setHorizontalGroup(
            panelRadius3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRadius3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
        );
        panelRadius3Layout.setVerticalGroup(
            panelRadius3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        jLabel4.setText("Tên giảng viên");

        cbbTenGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTenGiangVienActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã giảng viên");

        txtMaGiangVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaGiangVienActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã khóa học");

        cbbTenKhoaHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbTenKhoaHocActionPerformed(evt);
            }
        });

        jLabel6.setText("Tên khóa học");

        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setColor(new java.awt.Color(102, 0, 255));
        btnThem.setColorClick(new java.awt.Color(51, 0, 153));
        btnThem.setColorOver(new java.awt.Color(102, 0, 204));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setRoundBottomLeft(10);
        btnThem.setRoundBottomRight(10);
        btnThem.setRoundTopLeft(10);
        btnThem.setRoundTopRight(10);
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.setColor(new java.awt.Color(102, 0, 255));
        btnSua.setColorClick(new java.awt.Color(51, 0, 153));
        btnSua.setColorOver(new java.awt.Color(102, 0, 204));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setRoundBottomLeft(10);
        btnSua.setRoundBottomRight(10);
        btnSua.setRoundTopLeft(10);
        btnSua.setRoundTopRight(10);
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.setColor(new java.awt.Color(102, 0, 255));
        btnXoa.setColorClick(new java.awt.Color(51, 0, 153));
        btnXoa.setColorOver(new java.awt.Color(102, 0, 204));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setRoundBottomLeft(10);
        btnXoa.setRoundBottomRight(10);
        btnXoa.setRoundTopLeft(10);
        btnXoa.setRoundTopRight(10);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRadius1Layout = new javax.swing.GroupLayout(panelRadius1);
        panelRadius1.setLayout(panelRadius1Layout);
        panelRadius1Layout.setHorizontalGroup(
            panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelRadius3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelRadius1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRadius1Layout.createSequentialGroup()
                        .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbTenGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(109, 109, 109)
                        .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbTenKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(txtMaKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelRadius1Layout.createSequentialGroup()
                        .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        panelRadius1Layout.setVerticalGroup(
            panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRadius1Layout.createSequentialGroup()
                .addComponent(panelRadius3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbbTenKhoaHoc)
                    .addComponent(cbbTenGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaGiangVien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaKhoaHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(panelRadius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 94, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(471, 471, 471))
                    .addComponent(panelRadius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbb_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbb_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelRadius1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaGiangVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaGiangVienActionPerformed

    private void txtTimKiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyTyped
        // TODO add your handling code here:
            String value = cbb_TimKiem.getSelectedItem().toString();
            switch(value){
                case "Mã giảng viên":
                    char c = evt.getKeyChar();
                    if(!Character.isDigit(c))
                        evt.consume();
                    break;
                case "Mã khóa học":
                    char d = evt.getKeyChar();
                    if(!Character.isDigit(d))
                        evt.consume();
                    break;
            }

    }//GEN-LAST:event_txtTimKiemKeyTyped

    
    
    
    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtTimKiemKeyPressed

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
        try {
            // TODO add your handling code here:
            String value = cbb_TimKiem.getSelectedItem().toString();
            switch(value){
                case "Tên giảng viên":
                    if(txtTimKiem.getText().isEmpty())
                        listCI();
                    else
                        findNameInstructor(txtTimKiem.getText());
                    break;
                case "Mã giảng viên":
                    if(txtTimKiem.getText().isEmpty())
                        listCI();
                    else
                        findIdInstructor(txtTimKiem.getText());
                    break;
                case "Tên khóa học":
                    if(txtTimKiem.getText().isEmpty())
                        listCI();
                    else
                        findNameCourse(txtTimKiem.getText());
                    break;
                case "Mã khóa học":
                    if(txtTimKiem.getText().isEmpty())
                        listCI();
                    else
                        findIdCourse(txtTimKiem.getText());
                    
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try {
            // TODO add your handling code here:
            model = (DefaultTableModel) table.getModel();
            int i = table.getSelectedRow();
            if(i>=0){
                sOld.setCourseID(Integer.parseInt(model.getValueAt(i, 1).toString()));
                sOld.setPersonID(Integer.parseInt(model.getValueAt(i, 3).toString()));
                txtMaGiangVien.setText(model.getValueAt(i, 3).toString());
                cbbTenGiangVien.setSelectedItem(model.getValueAt(i, 4).toString());
                cbbTenKhoaHoc.setSelectedItem(model.getValueAt(i, 2).toString());
                txtMaKhoaHoc.setText(model.getValueAt(i, 1).toString());
            }
            JTable source = (JTable)evt.getSource();
            int columnindex = table.getSelectedColumn();
            int row = source.rowAtPoint( evt.getPoint() );
            int column = source.columnAtPoint( evt.getPoint() );
            //            JOptionPane.showMessageDialog(null, temp);
            switch (columnindex) {
                case 1:
                    String temp = source.getModel().getValueAt(row, column)+"";
//                JOptionPane.showMessageDialog(null, temp);
                    ArrayList ListOnsite = sBll.getCourseAndOnsiteCourseById(Integer.parseInt(temp));
                    if(ListOnsite.isEmpty()){
                        ArrayList ListOnline = sBll.getCourseAndOnlinesiteCourseById(Integer.parseInt(temp));
                        dialog_OnlineId.setText(ListOnline.get(0).toString());
                        dialog_onlineName.setText(ListOnline.get(1).toString());
                        dialog_onlineCredit.setText(ListOnline.get(2).toString());
                        dialog_onlineDep.setText(ListOnline.get(3).toString());
                        dialog_onlineUrl.setText(ListOnline.get(4).toString());
                        jDialog_OnlineCourse.show();
                    }
                    else{
                        dialog_id.setText(ListOnsite.get(0).toString());
                        dialog_name.setText(ListOnsite.get(1).toString());
                        dialog_credit.setText(ListOnsite.get(2).toString());
                        dialog_idDepart.setText(ListOnsite.get(3).toString());
                        dialog_location.setText(ListOnsite.get(4).toString());
                        dialog_days.setText(ListOnsite.get(5).toString());
                        dialog_time.setText(ListOnsite.get(6).toString());
                        JDialog_OnSiteCourse.show();
                    }
                    
                    break;
                default:
                    throw new AssertionError();
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tableMouseClicked

    private void cbbTenGiangVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTenGiangVienActionPerformed
        // TODO add your handling code here:
        if(cbbTenGiangVien.getSelectedIndex()==-1){
            
        }
        else
        {
            try {
                int result = s.getIdInstructorFromFullname(cbbTenGiangVien.getSelectedItem().toString());
                txtMaGiangVien.setText(Integer.toString(result));
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbbTenGiangVienActionPerformed

    private void cbbTenKhoaHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbTenKhoaHocActionPerformed
        // TODO add your handling code here:
        if(cbbTenKhoaHoc.getSelectedIndex()==-1){
            
        }
        else
        {
            try {
                int result = s.getIdCourserFromTitle(cbbTenKhoaHoc.getSelectedItem().toString());
                txtMaKhoaHoc.setText(Integer.toString(result));
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_cbbTenKhoaHocActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void tableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseEntered
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tableMouseEntered

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            CourseInstructorDTO ci = new CourseInstructorDTO(Integer.parseInt(txtMaKhoaHoc.getText()),Integer.parseInt(txtMaGiangVien.getText()), "", "");
            boolean isExist = s.isExistRecord(ci);
            if(isExist)
                JOptionPane.showMessageDialog(btnThem, "Giảng viên đã được phân công khóa này rồi, vui lòng chọn khóa khác");
            else{
                listCI();
                JOptionPane.showMessageDialog(btnThem, "Phân công thành công");
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int confirm =JOptionPane.showConfirmDialog(this,"Would you like to delete this course?","Confirm",JOptionPane.YES_NO_OPTION);
        if(confirm==JOptionPane.YES_OPTION){
          if(table.getSelectionModel().isSelectionEmpty() == true)
            JOptionPane.showMessageDialog(btnThem, "Vui lòng chọn khóa học để xóa");
            else{
            try {
            // TODO add your handling code here:
                CourseInstructorDTO ci = new CourseInstructorDTO();
                ci.setCourseID(Integer.parseInt(txtMaKhoaHoc.getText()));
                ci.setPersonID(Integer.parseInt(txtMaGiangVien.getText()));
                if(s.deleteCourseInstructor(ci)==0){
                    JOptionPane.showMessageDialog(this, "Delete failed");
                }
                else{
                    JOptionPane.showMessageDialog(this, "Delete success");
                    listCI();
                }
            } catch (SQLException ex) {
                Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }  
        }
        
    }//GEN-LAST:event_btnXoaActionPerformed

    CourseInstructorDTO sOld = new CourseInstructorDTO();
    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        CourseInstructorDTO sNew = new CourseInstructorDTO();
        sNew.setCourseID(Integer.parseInt(txtMaKhoaHoc.getText()));
        sNew.setPersonID(Integer.parseInt(txtMaGiangVien.getText()));
        try {
            if(s.updateCourseInstructor(sOld, sNew)==0){
                JOptionPane.showMessageDialog(this, "Update failed");
            }
            else{
                JOptionPane.showMessageDialog(this, "Update success");
                 listCI();
            }
        } catch (SQLException ex) {
            Logger.getLogger(QuanLyPhanCongGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void loadTenGiangVienCBB() throws SQLException{
        cbbTenGiangVien.setModel(new DefaultComboBoxModel<String>((String[]) s.readNameCourseInstructor().toArray(new String[0])));
    }
    
    private void loadTenKhoaHocCBB() throws SQLException{
        cbbTenKhoaHoc.setModel(new DefaultComboBoxModel<String>((String[]) s.readTitleCourseInstructor().toArray(new String[0])));
    }
    private DefaultTableModel convertCI(ArrayList list){
        String[] columnNames = {"TT","CourseID","Title","PersonID","FullName"};
        Object[][] data = new Object[list.size()][5];
        for(int i=0;i<list.size();i++){
            CourseInstructorDTO s = (CourseInstructorDTO) list.get(i);
            data[i][0]=i+1;
            data[i][1]=s.getCourseID();
            data[i][2]=s.getTitle();
            data[i][3]=s.getPersonID();
            data[i][4]=s.getFullName();
        }
        DefaultTableModel model = new DefaultTableModel(data,columnNames);
        return model;
    }

    private void findNameInstructor(String name) throws SQLException{
        CourseInstructorDTO ci = new CourseInstructorDTO(0,0,"",name);
        ArrayList list = s.findCourseInstructor(ci);
        DefaultTableModel model = convertCI(list);
        table.setModel(model);
    }
    
    private void findNameCourse(String name) throws SQLException{
        CourseInstructorDTO ci = new CourseInstructorDTO(0,0,name,"");
        ArrayList list = s.findCourseInstructor(ci);
        DefaultTableModel model = convertCI(list);
        table.setModel(model);
    }
    
    private void findIdInstructor(String name) throws SQLException{
        CourseInstructorDTO ci = new CourseInstructorDTO(0,Integer.parseInt(name),"","");
        ArrayList list = s.findCourseInstructor(ci);
        DefaultTableModel model = convertCI(list);
        table.setModel(model);
    }
    
    private void findIdCourse(String name) throws SQLException{
        CourseInstructorDTO ci = new CourseInstructorDTO(Integer.parseInt(name),0,"","");
        ArrayList list = s.findCourseInstructor(ci);
        DefaultTableModel model = convertCI(list);
        table.setModel(model);
    }
    
    private void listCI() throws SQLException{
        ArrayList list = s.readCourseInstructor();
        DefaultTableModel model = convertCI(list);
        table.setModel(model);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog JDialog_OnSiteCourse;
    private Custom.ButtonRadius btnSua;
    private Custom.ButtonRadius btnThem;
    private Custom.ButtonRadius btnXoa;
    private javax.swing.JComboBox<String> cbbTenGiangVien;
    private javax.swing.JComboBox<String> cbbTenKhoaHoc;
    private javax.swing.JComboBox<String> cbb_TimKiem;
    private javax.swing.JLabel dgoc_txt_IDCourse;
    private javax.swing.JLabel dgoc_txt_courseName;
    private javax.swing.JLabel dgoc_txt_credits;
    private javax.swing.JLabel dgoc_txt_idDepartment;
    private javax.swing.JLabel dgosc_txt_IDCourse;
    private javax.swing.JLabel dgosc_txt_Location;
    private javax.swing.JLabel dgosc_txt_courseName;
    private javax.swing.JLabel dgosc_txt_credits;
    private javax.swing.JLabel dgosc_txt_idDepartment;
    private javax.swing.JLabel dialog_OnlineId;
    private javax.swing.JLabel dialog_credit;
    private javax.swing.JLabel dialog_days;
    private javax.swing.JLabel dialog_id;
    private javax.swing.JLabel dialog_idDepart;
    private javax.swing.JLabel dialog_location;
    private javax.swing.JLabel dialog_name;
    private javax.swing.JLabel dialog_onlineCredit;
    private javax.swing.JLabel dialog_onlineDep;
    private javax.swing.JLabel dialog_onlineName;
    private javax.swing.JLabel dialog_onlineUrl;
    private javax.swing.JLabel dialog_time;
    private javax.swing.JDialog jDialog_OnlineCourse;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private Custom.PanelRadius panelRadius1;
    private Custom.PanelRadius panelRadius3;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtMaGiangVien;
    private javax.swing.JTextField txtMaKhoaHoc;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
